# Brews
brew 'bat'
brew 'cocoapods'
brew 'fastlane'
brew 'flyctl'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'httpie'
brew 'mas'
brew 'oven-sh/bun/bun'
brew 'python'
brew 'ripgrep'
brew 'starship'
brew 'trash-cli'
brew 'tree'
brew 'watchman'

# Casks
cask 'amazon-q'
cask 'android-studio'
cask 'apidog'
cask 'blender'
cask 'discord'
cask 'docker'
cask 'expo-orbit'
cask 'figma'
cask 'firefox'
cask 'ghostty'
cask 'google-chrome'
cask 'iina'
cask 'iterm2'
cask 'ledger-live'
cask 'microsoft-word'
cask 'microsoft-excel'
cask 'obsidian'
cask 'omnidisksweeper'
cask 'onedrive'
cask 'qbittorrent'
cask 'raycast'
cask 'supabase/tap/supabase'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'zulu@17' # https://docs.expo.dev/workflow/android-studio-emulator/#install-dependencies

# Mac App Store
mas 'AdGuard para Safari', id: 1440147259
mas 'Be Focused Pro', id: 961632517
