# Brews
brew 'bat'
brew 'bruno-cli'
brew 'cocoapods'
brew 'docker'
brew 'fastlane'
brew 'flyctl'
brew 'fnm'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'httpie'
brew 'mas'
brew 'oven-sh/bun/bun'
brew 'python'
brew 'rbenv'
brew 'ripgrep'
brew 'starship'
brew 'trash-cli'
brew 'tree'
brew 'watchman'

# Casks
cask 'android-studio'
cask 'blender'
cask 'bruno'
cask 'claude-code'
cask 'discord'
cask 'expo-orbit'
cask 'figma'
cask 'font-lilex'
cask 'firefox'
cask 'ghostty'
cask 'google-chrome'
cask 'kiro-cli'
cask 'iina'
cask 'ledger-live'
cask 'microsoft-excel'
cask 'microsoft-outlook'
cask 'microsoft-teams'
cask 'microsoft-word'
cask 'obsidian'
cask 'omnidisksweeper'
cask 'raycast'
# cask 'supabase/tap/supabase'  # Temporarily disabled - tap unavailable
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'zed'
cask 'zulu@17' # https://docs.expo.dev/workflow/android-studio-emulator/#install-dependencies

# Mac App Store
mas 'AdGuard para Safari', id: 1440147259
mas 'Be Focused Pro', id: 961632517
