export DEVELOPER="${HOME}/Developer"
export DOTFILES="${HOME}/.dotfiles"
export LOGSEQ="${HOME}/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents"
export OBSIDIAN="${HOME}/Library/Mobile Documents/iCloud~md~obsidian/Documents/"
export PNPM_HOME="${HOME}/Library/pnpm"
export ANDROID_HOME="${HOME}/Library/Android/sdk"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
